/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.catapult.excel.analyzer.ui;

import com.catapult.excel.analyzer.ExcelDataHeader;
import com.catapult.excel.analyzer.ExcelSheetAnalyzer;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.util.IOUtils;

/**
 *
 * @author jvergara <jvergara@gocatapult.com>
 */
public class AnalyzerUI extends javax.swing.JPanel
{
    private JFileChooser fileChooser;
    private Workbook workbook;
    private DefaultListModel listModel;

    /**
     * Creates new form AnalyzerUI
     */
    public AnalyzerUI()
    {
        initComponents();

        fileChooser = new JFileChooser();
        listModel = new DefaultListModel();
        lstSheetNames.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnBrowse = new javax.swing.JButton();
        txtFilename = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSheetNames = new javax.swing.JList();
        btnProcess = new javax.swing.JButton();

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBrowseActionPerformed(evt);
            }
        });

        txtFilename.setEditable(false);
        txtFilename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lstSheetNames.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstSheetNames.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstSheetNames);

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFilename)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBrowse)
                            .addComponent(btnProcess))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBrowseActionPerformed
    {//GEN-HEADEREND:event_btnBrowseActionPerformed
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) return;

        File file = fileChooser.getSelectedFile();
        txtFilename.setText("");
        listModel.clear();
        InputStream is = null;
        
        try {
            is = new FileInputStream(file);
            workbook = WorkbookFactory.create(is);
            txtFilename.setText(file.getAbsolutePath());
            for (int i=0; i < workbook.getNumberOfSheets(); ++i) {
                if (workbook.isSheetHidden(i)) continue;

                Sheet sheet = workbook.getSheetAt(i);
                listModel.addElement(sheet.getSheetName());
            }
        }
        catch(Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Invalid file selected", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally {
            IOUtils.closeQuietly(is);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnProcessActionPerformed
    {//GEN-HEADEREND:event_btnProcessActionPerformed
        if (lstSheetNames.getSelectedValue() == null) return;

        String name = lstSheetNames.getSelectedValue().toString();
        Sheet sheet = workbook.getSheet(name);

        System.out.println("-------------------------------------");
        System.out.println("Sheet Name: " + sheet.getSheetName());
        System.out.println("-------------------------------------");

        ExcelSheetAnalyzer analyzer = new ExcelSheetAnalyzer(sheet);
        analyzer.analyze();

        for (ExcelDataHeader header : analyzer.getHeaders()) {
            System.out.println(header);
        }

        JOptionPane.showMessageDialog(this, "Done!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnProcessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstSheetNames;
    private javax.swing.JTextField txtFilename;
    // End of variables declaration//GEN-END:variables
}
